### ISSUE TITLE
Punto 4 - elGranCandidato/1 - Nombre de predicado

### ISSUE THREAD

**Issue by fedejinich** [ma77hews/TpProlog2019#5]
`compararEdades(Candiadto, OtroCandidato)`

Ojo con el nombre que le ponen a sus predicados, son relaciones, no funciones!

En lo personal yo no me hago mucho eco de esto, pero se lo podrian marcar como error en el parcial

**Comment by ma77hews** [comment]
buen dato, lo puse asi porque era lo que hacia, seria un buen nombre unCandidatoMayorQueOtro ?

**Comment by fedejinich** [comment]
va bien, acordate que siempre se evalua la expresividad, asi que se claro con los nobmres y no escatimes palabras. Si te queda un nombre largo ya fue no hay drama
