### ISSUE TITLE
Punto 7 - influenciaPromesas/2 - Inversibilidad

### ISSUE THREAD

**Issue by fedejinich** [ma77hews/TpProlog2019#7]
Este predicado no es inversible

Todos los predicados tienen que serlo, salvo que se aclare lo contrario

**Comment by ma77hews** [comment]
el codigo ya esta subido, ahora creo que esta inversible =)

**Comment by fedejinich** [comment]
para que sea inversible, fijate solo con hacer consultas existenciales para todos los parametros del predicado 
- si es inversible para algunos, etnocnes el precidado es parcialmente inversible
- si es para todos es completamente inversible
