### ISSUE TITLE
Punto 8 - promedioDeCrecimiento/2 - Falta el punto entero

### ISSUE THREAD

**Issue by fedejinich** [ma77hews/TpProlog2019#9]
Eso

**Comment by ma77hews** [comment]
claramente era algo obvio jaja, 
ya subi el punto 8 Tambien 

`promedioDeCrecimiento(UnPartido, SumatoriaTotal):-
findall(Crecimiento,(promete(UnPartido,Promesa),influenciaDePromesas(Promesa,Crecimiento)),Crecimientos),
	sumlist(Crecimientos,SumatoriaTotal).`

**Comment by fedejinich** [comment]
bien ahi, eso es lo que se esperaba, reusar una abstraccion para solucionar un problema
